### ISSUE TITLE
Not rendering in Discord on Linux

### ISSUE THREAD

**Issue by Jenna64bit** [Gryzle/Neumorphism#1]
Hey there! This looks like it could be a great theme. I'm a huge fan of *eumorphic themes in general. However, after installing the plug in it doesn't render correctly in Linux. I get the color scheme but everything remains flat. For example, channel icons don't have a border. If you are still maintaining this theme, is there anything I can do to help troubleshoot?

**Comment by Gryzle** [comment]
This issue is present on all platforms including Windows, macOS, and Linux. I have no plans to update this theme as doing so would require finding and replacing every single class name that Discord may have changed in the past 15 months.
